export const SET_ALLIDANDTITLE = 'SET_ALLIDANDTITLE';
export const SET_CURRITEM = 'SET_CURRITEM';
export const SET_MESSAGES = 'SET_MESSAGES';
export const PUT_MESSAGE = 'PUT_MESSAGE';
export const CREATE_CODE = 'CREATE_CODE';
export const SET_CODEHEIGHT = 'SET_CODEHEIGHT';
